# Generated by Django 5.2.14 on 2026-05-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('id',)},
        ),
    ]
